// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYeO0sMAVNh-ORMd3rXwcw4TGqIdye6w',
    appId: '1:214163846244:web:aa4ccac3b46f9dbb525b71',
    messagingSenderId: '214163846244',
    projectId: 'oorja-4a18a',
    authDomain: 'oorja-4a18a.firebaseapp.com',
    storageBucket: 'oorja-4a18a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3QXZNUVLkNxANmCmZr7dOnEXyYXIBlcY',
    appId: '1:214163846244:android:13dc96e1c887559b525b71',
    messagingSenderId: '214163846244',
    projectId: 'oorja-4a18a',
    storageBucket: 'oorja-4a18a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyGc-B2vevB775UMPUgxUJi-1HuIzAbfg',
    appId: '1:214163846244:ios:eb5dceeed1f7e469525b71',
    messagingSenderId: '214163846244',
    projectId: 'oorja-4a18a',
    storageBucket: 'oorja-4a18a.firebasestorage.app',
    iosBundleId: 'com.example.oorja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyGc-B2vevB775UMPUgxUJi-1HuIzAbfg',
    appId: '1:214163846244:ios:eb5dceeed1f7e469525b71',
    messagingSenderId: '214163846244',
    projectId: 'oorja-4a18a',
    storageBucket: 'oorja-4a18a.firebasestorage.app',
    iosBundleId: 'com.example.oorja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBYeO0sMAVNh-ORMd3rXwcw4TGqIdye6w',
    appId: '1:214163846244:web:5256102de9826e6f525b71',
    messagingSenderId: '214163846244',
    projectId: 'oorja-4a18a',
    authDomain: 'oorja-4a18a.firebaseapp.com',
    storageBucket: 'oorja-4a18a.firebasestorage.app',
  );
}
